// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxhzhofwiugfxamqtbgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4aHpob2Z3aXVnZnhhbXF0YmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjM2OTMsImV4cCI6MjA2NjM5OTY5M30.-HpQoR_hqodLpdKMWG2IXqZpSPq3HgQP04IcEq_6ppI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);